name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo s string
        run: echo "Hello World!!"
      - name: multiline script
        run: |
          java -version
      - name: Python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python